[2024-04-30T20:31:57.540+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-30T20:31:57.553+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_api_extraction manual__2024-04-30T20:31:54.190399+00:00 [queued]>
[2024-04-30T20:31:57.557+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_api_extraction manual__2024-04-30T20:31:54.190399+00:00 [queued]>
[2024-04-30T20:31:57.558+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-30T20:31:57.565+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): reddit_api_extraction> on 2024-04-30 20:31:54.190399+00:00
[2024-04-30T20:31:57.572+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2024-04-30T20:31:57.584+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_api_extraction', 'manual__2024-04-30T20:31:54.190399+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/redditDag.py', '--cfg-path', '/tmp/tmpcoc9oyba']
[2024-04-30T20:31:57.591+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask reddit_api_extraction
[2024-04-30T20:31:57.775+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_api_extraction manual__2024-04-30T20:31:54.190399+00:00 [running]> on host bfcdeb2a62e6
[2024-04-30T20:31:57.886+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Vaibhav Sharma' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_api_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T20:31:54.190399+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-30T20:31:54.190399+00:00'
[2024-04-30T20:31:57.887+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-30T20:31:57.898+0000] {logging_mixin.py:188} INFO - connected to reddit!
[2024-04-30T20:31:58.119+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-30T20:31:58.119+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/redditPipeline.py", line 12, in reddit_pipeline
    posts = extract_posts(instance, subreddit, time_filter, limit)
  File "/opt/airflow/etls/redditEtl.py", line 29, in extract_posts
    for post in posts:
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 63, in __next__
    self._next_batch()
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/models/listing/generator.py", line 89, in _next_batch
    self._listing = self._reddit.get(self.url, params=self.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 712, in get
    return self._objectify_request(method="GET", params=params, path=path)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 517, in _objectify_request
    self.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/util/deprecate_args.py", line 43, in wrapped
    return func(**dict(zip(_old_args, args)), **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/praw/reddit.py", line 941, in request
    return self._core.request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 328, in request
    return self._request_with_retries(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 234, in _request_with_retries
    response, saved_exception = self._make_request(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 186, in _make_request
    response = self._rate_limiter.call(
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/rate_limit.py", line 46, in call
    kwargs["headers"] = set_header_callback()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 282, in _set_header_callback
    self._authorizer.refresh()
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 378, in refresh
    self._request_token(grant_type="client_credentials", **additional_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 155, in _request_token
    response = self._authenticator._post(url=url, **data)
  File "/home/airflow/.local/lib/python3.9/site-packages/prawcore/auth.py", line 59, in _post
    raise ResponseException(response)
prawcore.exceptions.ResponseException: received 401 HTTP response
[2024-04-30T20:31:58.130+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_api_extraction, execution_date=20240430T203154, start_date=20240430T203157, end_date=20240430T203158
[2024-04-30T20:31:58.139+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task reddit_api_extraction (received 401 HTTP response; 65)
[2024-04-30T20:31:58.183+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-30T20:31:58.204+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-30T20:31:58.206+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
